// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using React.Data;

#nullable disable

namespace React.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FixedAssetProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChangeRequestId")
                        .HasColumnType("int")
                        .HasColumnName("change_request_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("product_code");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("ProductCode")
                        .IsUnique()
                        .HasFilter("[product_code] IS NOT NULL");

                    b.ToTable("fixed_asset_products");
                });

            modelBuilder.Entity("FixedAssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("fixed_asset_types");
                });

            modelBuilder.Entity("Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HolidayId");

                    b.HasIndex("HolidayDate");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("React.Models.AnnualLeave", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("entitlement")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("annual_leave");
                });

            modelBuilder.Entity("React.Models.Attendance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_submission")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("time_in")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("time_in_photo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("time_out")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("time_out_photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("React.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("CertificateContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("certificate_content");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("file_type");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int")
                        .HasColumnName("training_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("React.Models.ChangeRequest", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ApprovalSignatureId")
                        .HasColumnType("int")
                        .HasColumnName("approval_signature_id");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("approver_id");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("complete_date");

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_approved");

                    b.Property<DateTime?>("DateRequested")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_requested");

                    b.Property<DateTime?>("DateReturned")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_returned");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("FixedAssetTypeId")
                        .HasColumnType("int")
                        .HasColumnName("fixed_asset_type_id");

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instruction");

                    b.Property<string>("PostReview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_review");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("ReceivedDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("received_details");

                    b.Property<int?>("RequesterId")
                        .HasColumnType("int")
                        .HasColumnName("requester_id");

                    b.Property<string>("ReturnStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("return_status");

                    b.Property<string>("Risk")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("risk");

                    b.Property<int?>("SignatureId")
                        .HasColumnType("int")
                        .HasColumnName("signature_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalSignatureId");

                    b.HasIndex("ApproverId");

                    b.HasIndex("FixedAssetTypeId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("SignatureId");

                    b.ToTable("ChangeRequests");
                });

            modelBuilder.Entity("React.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("React.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("doc_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("doc_content");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<byte[]>("DocumentUpload")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("doc_upload");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("file_type");

                    b.Property<int>("PostBy")
                        .HasColumnType("int")
                        .HasColumnName("post_by");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("post_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PostBy");

                    b.HasIndex("PostDate");

                    b.HasIndex("Type");

                    b.ToTable("documents", "dbo");
                });

            modelBuilder.Entity("React.Models.DocumentRead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocId")
                        .HasColumnType("int")
                        .HasColumnName("doc_id");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_date");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DocId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentReads");
                });

            modelBuilder.Entity("React.Models.EquipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justification");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("equipment_items");
                });

            modelBuilder.Entity("React.Models.EquipmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovalSignatureId")
                        .HasColumnType("int")
                        .HasColumnName("approval_signature_id");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("approver_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_approved");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_requested");

                    b.Property<string>("ReceivedDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("received_details");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int")
                        .HasColumnName("requester_id");

                    b.Property<int>("SignatureId")
                        .HasColumnType("int")
                        .HasColumnName("signature_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalSignatureId");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("SignatureId");

                    b.ToTable("equipment_requests", "dbo");
                });

            modelBuilder.Entity("React.Models.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("date");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("React.Models.HandbookContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HandbookSectionId")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HandbookSectionId");

                    b.ToTable("HandbookContents");
                });

            modelBuilder.Entity("React.Models.HandbookSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HandbookSections");
                });

            modelBuilder.Entity("React.Models.LeaveDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("annual_leave_id")
                        .HasColumnType("int");

                    b.Property<int?>("approval_signature_id")
                        .HasColumnType("int");

                    b.Property<int?>("approved_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_submission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("leave_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("leave_end_date")
                        .HasColumnType("datetime2");

                    b.Property<double>("no_of_days")
                        .HasColumnType("float");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("leave_detail");
                });

            modelBuilder.Entity("React.Models.LeaveRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_submission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("total_day")
                        .HasColumnType("int");

                    b.Property<byte[]>("url")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("id");

                    b.ToTable("Mc_Leave_Requests");
                });

            modelBuilder.Entity("React.Models.Moment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CreatedAt", "Id");

                    b.ToTable("Moments");
                });

            modelBuilder.Entity("React.Models.MomentImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MomentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MomentId");

                    b.ToTable("MomentImages");
                });

            modelBuilder.Entity("React.Models.MomentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MomentId")
                        .HasColumnType("int");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MomentId");

                    b.HasIndex("UserId");

                    b.ToTable("MomentReactions");
                });

            modelBuilder.Entity("React.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarouselType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastEditedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastEditedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextCn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("React.Models.QuoteReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReactedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteReactions");
                });

            modelBuilder.Entity("React.Models.QuoteView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViewedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteViews");
                });

            modelBuilder.Entity("React.Models.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BoundaryHeight")
                        .HasColumnType("float")
                        .HasColumnName("boundary_height");

                    b.Property<double>("BoundaryWidth")
                        .HasColumnType("float")
                        .HasColumnName("boundary_width");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("points");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("React.Models.TrainingCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CourseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("course_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("training_courses");
                });

            modelBuilder.Entity("React.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday");

                    b.Property<DateTime?>("ChangePasswordDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("change_password_date");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_joined");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("EPFNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("epf_no");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FcmToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FCMToken");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("NRIC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nric");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("TIN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tin");

                    b.Property<string>("active_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("active_status");

                    b.Property<string>("contactNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_number");

                    b.Property<string>("nickname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nickname");

                    b.Property<byte[]>("profile_picture")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("profile_picture");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NRIC")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FixedAssetProduct", b =>
                {
                    b.HasOne("React.Models.ChangeRequest", "ChangeRequest")
                        .WithMany("FixedAssetProducts")
                        .HasForeignKey("ChangeRequestId");

                    b.Navigation("ChangeRequest");
                });

            modelBuilder.Entity("React.Models.Certificate", b =>
                {
                    b.HasOne("React.Models.TrainingCourse", "TrainingCourse")
                        .WithMany("Certificates")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingCourse");
                });

            modelBuilder.Entity("React.Models.ChangeRequest", b =>
                {
                    b.HasOne("React.Models.Signature", "ApprovalSignature")
                        .WithMany()
                        .HasForeignKey("ApprovalSignatureId");

                    b.HasOne("React.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("FixedAssetType", "FixedAssetType")
                        .WithMany()
                        .HasForeignKey("FixedAssetTypeId");

                    b.HasOne("React.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId");

                    b.HasOne("React.Models.Signature", "Signature")
                        .WithMany()
                        .HasForeignKey("SignatureId");

                    b.Navigation("ApprovalSignature");

                    b.Navigation("Approver");

                    b.Navigation("FixedAssetType");

                    b.Navigation("Requester");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("React.Models.Document", b =>
                {
                    b.HasOne("React.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("React.Models.User", "Poster")
                        .WithMany()
                        .HasForeignKey("PostBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("React.Models.DocumentRead", b =>
                {
                    b.HasOne("React.Models.Document", "Document")
                        .WithMany("DocumentReads")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("React.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("React.Models.EquipmentItem", b =>
                {
                    b.HasOne("React.Models.EquipmentRequest", "Request")
                        .WithMany("Items")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("React.Models.EquipmentRequest", b =>
                {
                    b.HasOne("React.Models.Signature", "ApprovalSignature")
                        .WithMany("ApprovalSignatures")
                        .HasForeignKey("ApprovalSignatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("React.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("React.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("React.Models.Signature", "Signature")
                        .WithMany("RequestSignatures")
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalSignature");

                    b.Navigation("Approver");

                    b.Navigation("Requester");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("React.Models.HandbookContent", b =>
                {
                    b.HasOne("React.Models.HandbookSection", "HandbookSection")
                        .WithMany("Contents")
                        .HasForeignKey("HandbookSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HandbookSection");
                });

            modelBuilder.Entity("React.Models.Moment", b =>
                {
                    b.HasOne("React.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("React.Models.MomentImage", b =>
                {
                    b.HasOne("React.Models.Moment", "Moment")
                        .WithMany("Images")
                        .HasForeignKey("MomentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moment");
                });

            modelBuilder.Entity("React.Models.MomentReaction", b =>
                {
                    b.HasOne("React.Models.Moment", "Moment")
                        .WithMany("Reactions")
                        .HasForeignKey("MomentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("React.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Moment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("React.Models.QuoteReaction", b =>
                {
                    b.HasOne("React.Models.Quote", "Quote")
                        .WithMany("Reactions")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("React.Models.QuoteView", b =>
                {
                    b.HasOne("React.Models.Quote", "Quote")
                        .WithMany("Views")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("React.Models.Signature", b =>
                {
                    b.HasOne("React.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("React.Models.TrainingCourse", b =>
                {
                    b.HasOne("React.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("React.Models.User", b =>
                {
                    b.HasOne("React.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("React.Models.ChangeRequest", b =>
                {
                    b.Navigation("FixedAssetProducts");
                });

            modelBuilder.Entity("React.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("React.Models.Document", b =>
                {
                    b.Navigation("DocumentReads");
                });

            modelBuilder.Entity("React.Models.EquipmentRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("React.Models.HandbookSection", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("React.Models.Moment", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("React.Models.Quote", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("React.Models.Signature", b =>
                {
                    b.Navigation("ApprovalSignatures");

                    b.Navigation("RequestSignatures");
                });

            modelBuilder.Entity("React.Models.TrainingCourse", b =>
                {
                    b.Navigation("Certificates");
                });
#pragma warning restore 612, 618
        }
    }
}
